-- Database Used : LiveSQL Oracle
--Q3. 'Sickest' Floor

SELECT Floor_ID, COUNT(*) AS Symptom_Count
FROM MEETING
INNER JOIN SYMPTOM ON MEETING.Emp_ID = SYMPTOM.Emp_ID
WHERE Date_Reported BETWEEN TO_DATE('2023-01-01','YYYY-MM-DD') AND TO_DATE('2024-12-12','YYYY-MM_DD') 
GROUP BY Floor_ID
ORDER BY Symptom_Count DESC
FETCH FIRST 1 ROW ONLY;